name                      = "nl004pa-tayler-dev"
location                  = "WestEurope"
network_address_space     = "10.0.0.0/16"
aks_subnet_address_name   = "akssubnet"
aks_subnet_address_prefix = "10.0.1.0/24"
subnet_address_name       = "appgwsubnet"
subnet_address_prefix     = "10.0.0.0/27"
